[package]
name = "http-compress"
version = "0.0.1"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = """A lightweight library for decompressing HTTP responses supporting Brotli, Deflate, and Gzip."""
keywords = ["http", "request", "response", "tcp", "redirect"]
repository = "https://github.com/ltpp-universe/http-compress.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "sh",
    ".github"
]

[dependencies]
brotli = "7.0.0"
flate2 = "1.0.35"
http-constant = "1.0.0"
http-type = "0.0.2"
